<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DreamsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dreams = [
            ['dream' => 'Egy Szárnyas Fejvadásszerű jelenetben vagyok, fogalmam sincs, hogy kerülök ide. A főszereplő Ryan Gosling, de kicsit mintha én is benne lennék. Ő is hallgatja a híreket és ennek megfelelően indul küldetésére. A következő jelenetben egy padlásszobaszerű műteremben rajzolok vagy rajzolunk együtt valakivel, talán egy nővel. Pasztell rajz készül. Ott hagyjuk őket a földön, elmegyünk valahova, de bejön a macskája és rászól, hogy ne gyalogoljon végig a rajzokon. Ő elmegy, de én visszafordulok és egy vékony fóliát teszek a rajzra, hogy ezzel védjem meg a macskától. A következő jelenet szinte összefüggéstelenül jön. Egy fiatal lány, 20-25 éves, rövid barna hajú, szép arcú, csinos. Talán vele készítettem a rajzot. Randevúra készül, biztos benne, hogy az anyja nem fogja elengedni, ezért igazából meg sem kérdezi, hogy elmehet-e. Nem egyértelmű, hogy az anyának a randival van baja vagy azzal, hogy a lány taxival akar menni. Mindenesetre teljes díszben megjelenik a fényűző világos ház halljában és a sötétbarna hajába nagyon szépen beleillik a hajráf, amire sárga taxi feliratú kis dísz került. Menne is tovább, de épp belefut az anyjába, aki szintén nagyon szép, fiatalos és látszólag jómódú. Kicsit hasonlít anyukámra az arca. A lány legnagyobb meglepetésére különösebb fennakadás nélkül, mosolyogva és zokszó nélkül engedi el útjára, búcsúzóul még meg is puszilja, ahogy a lány kilép az utcára. Már várja a taxi. Az utcán végignézve hátrafordul és meglát egy üzlethelyiséget, ami akkor nyit ki. Nem tudom, ezt nem látom pontosan, de valami nagyon színes kirakat. Nincs jelentősége, elmennek.'],
            ['dream' => 'Munkatársaimmal verődtem csapatba és vonultunk helyről helyre, átszeltünk egy teret, ahol piacoztak, alapvetően egy éhes horda voltunk, aki enni akart. Valahova tartottunk, de az még túl távolinak tűnt, a piacon próbáltunk venni ezt-azt. Később egy épületen át meneteltünk, ami hirtelen annyira beszűkült, hogy hason csúszva kellett mászni előre. Egy tömör, klasszicista, kő átjáró alatt haladtunk, ahol pont annyi hely volt az oszlopok és a padló között, hogy hason csúszva a fejünk átférjen. Ez nem mindenhol sikerült, még így is túl szűknek bizonyult néhány nyílás. Később más milyenre váltott az épület, egy nagy, faburkolatú hodály lett belőle, ahol elkeveredtem a többiektől, amikor elmentem mosdóba és ők lehagytak. Próbáltam telefonálni, de nem sikerült. A telefont hiába vettem a kezemben, nem tudtam használni. Később megtalálom őket sok bolyongás után a tetőteraszon, innentől elhalványul a jelenet.'],
            ['dream' => 'Egy kisbabára vigyáztam, amikor el kellett ugranom valamiért. Mondtam, hogy csak egy megálló, gyorsan megjárom. A villamoson viszont elaludtam, így továbbmentem és amikor felébredtem, rájöttem, hogy egy erdő közepén vagyok a semmiben. Sötét van és nem is villamosra, hanem buszra szálltam, amivel ráadásul nem is tudtam, hova jutottam. A megálló után feltűnt egy csomó óriás schnauzer, akik ki tudtak ugrani a kerítésen. Féltem tőlük, igyekeztem húzódni emberekhez. Végül feljutottam egy házba, ami a G-é volt, egy magas, újépítésű, csodásan berendezett nagy ház, annak is a felső emeletén. Majd leereszkedtem és kerestem a visszafelé vezető utat.'],
            ['dream' => 'Kiállítást rendeztünk. R 3D modellt készített a térről és mutatta nekem a rendezést.'],
            ['dream' => 'Álltam és láttam, hogy folyik alattam a víz mindenfele, kis folyókban vagy csermelyekben. A lában süllyed le, sötétbarna volt a föld, a vizet nem is láttam, csak éreztem, hogy a víz jön fel.'],
            ['dream' => 'Vezetek egy autót egy pályán, ahol ugyan vannak sávok, de senki nem tartja be a szabályokat. Jönnek szemből az autók, néha ugyanazon a sávon, aztán vagy kitérnek, vagy előlük kell kitérni.'],
            ['dream' => 'Amikor hazaértem a szüleim lakásába, B már az ágyban feküdt fejtetőig betakarózva és aludt. Befeküdtem hozzá, hogy köszöntsem, mire egy óriási egeret látok a feje mellett. Elkezdek sikongatni, ő nagyon nehezen mozdul, miközben szerencsétlenkedük az egérrel, a párkányon látok egy parányi egeret is összenyomva. A nagyobb példányt végső elhatározásra a kezembe veszem és olyan erősen szorítom, mindent beleadva, miközben ficánkol, hogy mire kiérek az erkélyajtóig, már nem mozog többet.'],
            ['dream' => 'Apukám születésnapjára készülünk, én még a hazautazás előtt állok. Anyukámmal egyeztetek lázasan telefonon. Éppen bedobtam az ötletet, hogy jöjjenek fel hozzám a fővárosba, mert itt sokkal több a szórakozási és kikapcsolódási lehetőség és itt igazán különlegessé lehetne tenni a szülinapot. Nekem is sokkal egyszerűbb lenne helyben maradni, ha ők jönnek fel. Ezen a ponton kiderült, hogy apu már lefoglalt egy quad motorozást valahol a Dél-Alföldön, amitől teljesen eldobom az agyam, mert az a legtávolabb áll attól, amit én elképzeltem. Dehát ez az ő születésnapja. Közben az egyik telefonbeszélgetés, amit anyuval erről intézünk, az Aldiban vagy Lidlben zajlik és próbálok összevásárolni dolgokat, amiből majd főzök talán nekik az ünneplésre. Cukkinit veszek, amit apu utál. Aztán valahogy hazamegyek hozzájuk, már nem tudom hogyan, de a következő a jelenetben már otthon vagyok náluk és kipakolom az asztalra kis indulattal a bizonyos megvásárolt élelmiszereket. Természetesen addigra kiderül, hogy anya már mindent megfőzött. Készülődünk. A ház az az előző házunk, nem a mostani.'],
            ['dream' => 'Vizsgára készülök, ami másnap lesz, a lakásomban vagyok, ami egy káosz. Takarítanom kéne, de inkább csak össze-vissza öltözködöm kapkodva. Jön fel hozzám a M, aki miatt fel-le dobálom magamról a ruhákat. Rengeteg réteg van rajtam, leszedek mindent a legalsó fekete body-ig. Amikor belenézek a tükörbe, hosszú barna hajam van, ami vizesen esik a vállamra. Meglepődök, amikor elfordul a zár, hogy saját kulccsal jön be. Energikusan lép be, nagydarab és kivillan a bicepsze. Amint belép, a nyakába borulok. Számon kérem, hogy hogyan jött be, mire megsértődik vagy csak úgy tesz és húzza az agyamat. Utána ez az egész eltűnik és csak chatelünk, megírom neki, hogy anyukám beteg. CAPS LOCK-kal. Ami már akkor elég furán veszi ki magát, hiszen egész más céllal és hangulatban levelezünk. Utána már csak azt ismételgetem magamban, hogy Asperger-szindrómája van, de nem anyukámnak, hanem a M-nak.'],
            ['dream' => 'Itt vagyok a munkahelyemen, a P laptopjával szórakozok. A képernyőméret képes volt dinamikusan változni, szét tudtam húzni a kezemmel szélesvásznúra, majd összenyomni nagyon kicsire. Kiderült, hogy valaki tervezett egy olyan interface-t, aminek hosszúkás, téglány alakú volt a formátuma, emiatt alakították ki így a laptopot is, hogy pontosan az interface-re illeszkedjen. Járkálok a munkahelyemen fel s alá, miközben a képernyőt húzogatom és nyomkodom a nagy gombjait.'],
            ['dream' => 'Tartottam valahova, egy idegen hely felé, a csatornafedőknél nagyobb tányérszerű tárgyak fedték a fém lyukakat, amik tarkították az utat. Ahogy haladtam köztük, mindig majdnem beleestem. Folyton akadályokkal találkoztam. Aztán jöttek a G-ék, apukája, anyukája, betereltek egy nagy házba, ahova betért egy madár, talán galamb is, amit elkezdtek kergetni.'],
            ['dream' => 'El kellett mennem Oroszországba. El kellett érnem a last minute vonatot és apu elvitt Csernyőbe, ami egy szlovák város az ukrán határ mellett. Van egy titkos pályaudvara, ami Ukrajnában található, eddig nem tudtunk róla, monumentális brutalista épület volt az egész, egy nagy beton tömeg. Kiderült, hogy vízumot kell szereznem, amire elég ráparáztam. Menet közben a hotelben adtak vízumot, de kellett még valami plusz engedély, mielőtt belépsz az országba. A hotelbe azért beengedtek, és ott kaptam meg a vízumot. A hotel belülről faburkolatos, Wes Anderson-filmekre emlékeztető kialakítású volt. Végül az egész egy nagy fesztivállá alakult, ahol volt pár dj haverom, például a Pólós Zoli aka Planet Malcolm. Ő így is nagyon magas termetű, de még magasabbra nőtt, kétszer magasabb volt mint én. Úgy kellett rá felnéznem.'],
            ['dream' => 'Van egy nő, aki a férjével él egy távoli faluban, a nő az nagyon sovány, valamiért fél a férjétől, aki bántja. A nő pedig arra készül, hogy – ezt csak így távolról látom és nem vagyok testileg jelen csak a hangommal... Van előttem egy kis fából összerakott kalyiba, ami el van függönyözve fehér lepedőkkel és azok közé elrejtett egy liter tejet meg egy kenyeret és azokat szerelte rá különböző ilyen nagyobb kavicsokra és azzal edzett, aztán elment futni. Egész végig azt gondolta magában, hogy “ezt ki kell bírnom, ki kell bírnom”. Még egyik nap elhatározta, hogy tényleg elmegy. Állítólag a férje levette a jegygyűrűjét. Elindult futva, közben én magasból látom ezt az egész települést, és a férje egy másik irányba futott, a nő meg ellenkezőleg és közben a nő azt gondolta, hogy, vagy én azt gondoltam a nőről, hogy megérte ennyit gyakorolni vagy edzeni, mert sokkal gyorsabban fut és nem adja fel. Aztán a nő talált egy ilyen kis kalyibát az egyik háznak a kertjébe, ahova bezárkózott, vagy nem bezárkózott, hanem behúzta azt a két tolóajtót és leült a földre és azon gondolkodott, hogy vajon hazamenjen-e vagy se. Egy nagy fehér kutya volt az ajtóban és rátette a rekeszt.'],
            ['dream' => 'P ott van nálunk, a hálószobában vagyunk elszállásolva. Előbb felkelek, hogy felöltözzek, valami vagány cuccot akarok magamra rántani, de semmi nem jön rám vagy csak nehezen. A másik szobában a húgom készülődik, megkérem, hogy hagyja, hogy mi ketten menjünk át a boltba P-vel, ne jöjjön velünk. Nehezen érti meg, hogy tetszik nekem, valószínűleg ő is akarja. Egyszer csak csengetnek. Feljön hozzánk az alsó szomszédunk kisfia, aki egy csodálatosan gyönyörű, szőke kisfiú, a világ legszebb gyereke. Rögtön magamhoz veszem és ölelgetem. Nincs rajtam melltartó, így szorítom oda a fejét a mellemhez. Közben felkelt P és lát minket, ahogy játszunk és arra gondolok, hogy talán hasonlítok arra a nőre, akit szeret és most ezen jár a feje.'],
            ['dream' => 'Az előző házban vagyok, ahol korábban laktam. Nem pont ugyanúgy néz ki mint a valóságban, de az alapja megmaradt. A legfontosabb eltérés, hogy van erkély, pedig ebben a házban nem voltak erkélyes lakások. Mindenesetre azon az erkélyen vagy gangon ült kint egy baráti társaság és zenéltek és énekeltek viszonylag hangosan. Pedig ez a ház annyira nem bírta soha a bulikat, az idő múlását pedig úgy érzékeltem, hogy senki sem volt már ott a régi szomszédok közül. Bandáztunk és haverkodtunk, aztán az egész mintha egy hosztellé változott volna, nagyon nyitott lett és mozgalmas. Nem vadult be, inkább barátságosan, mintha Kapolcs meg a Művészetek völgye hangulata költözött volna be a házba. Egy idő után még az udvaron is voltak ilyen kis spontán zenélgetések, olyan jó hangulata volt.'],
            ['dream' => 'Repülőtérre mentünk a feleségemmel. Úgy nézett ki, mintha egy bangladesi pláza lenne, kicsit szocis építmény (a kis cernyoi vasútállomásra hasonló, amelyik közel van a magyar-szlovák-ukrán hármas határhoz). Nem kellett check-inelni a járatra, viszont a kijelzőkön nem írták ki, hogy mikor is kell felszállnunk a gépre. Utólag kiderült az infopultnál, hogy tulajdonképpen a háttérben többször is megváltoztatták a járat idejét és a célállomását is! Elkezdtünk rohanni a feleségemmel, valahogy lett egy kutyánk is. Óra harminckor indult a gép és óra harminckor kezdtünk el rohanni. Egy kínai család is elrohant előttünk. Plázán, mozgólépcsőn, majd egy pálmafákkal és kopott fűvel körbeölelt hosszú betonjárdán szaladtunk végig az épület oldalában, egészen a repülőig. Forró volt a levegő, a repülőnek voltak vizisiklós lábazatai. Sok pilóta volt, de csak egy kis növésű, alacsony, kövér vezetett és figyelt oda az útra. Felszállás után labilissá vált az utazás. Városi gyárépületeket hagytunk el és felszálláskor az egyik épülettetőnek neki pattant a repülő lábazata. Ezután mindenki ideges volt. Kis repülés után elkezdtünk lezuhanni egy folyó felett. Mi kipottyantunk a feleségemmel es a kutyámmal a folyóba, de csak kisebb sérülések értek. A többiek lezuhantak a városba és mind meghaltak, egy ember kivételével. A hírek szétszóródtak a médiában az esettel kapcsolatban. Miután kijutottunk a kórházból, a kollégámmal chateltem Slack-en az esetről. Elmagyaráztam neki, hogy mi jól vagyunk. Fotókkal támasztottam alá, hogy mi történt velünk. Képszakadás után már a kollégám asztala előtt álltam, a képernyőjén a chatelésünket látva. Ekkor megerősítettem, hogy most már folytathatjuk a VR projekt fejlesztését és minden rendben van.'],
            ['dream' => 'Összeülünk az Á-val és az A-val, hogy beszéljünk egy közös kiállítás-tervezetről, ami a munkáról szól. Az én témám már teljesen ki van dolgozva, de nem hagynak szóhoz jutni, hogy elmondjam. A dobál be dátumokat, amik egyre jobban összezavarnak, kiderül, hogy ezek mind egy-egy napok, külön, elválasztva. Értetlenkedek, neki pedig nem tetszik, hogy ezt teszem. Majd egy óriási házba kerülök egy erdős-mocsaras területen egyedül. Valami zörejt hallok az egyik fronton, ahol egy bambuszerdő terül el, látom, hogy a J próbál nekem valamit elmutogatni, de ebben a pillanatban a ház másik oldala felől beront egy társaság, akik között ott van a B is teljesen lerészegedve. Dülöngél és be akar feküdni a szobámba, világát se tudva, de én átgondolom, hogy ezzel mekkora fájdalmat fog okozni másnap, amikor majd felkelek és nem akar majd. Áttessékelem egy másik szobába, ahol leheveredik az első ágyra, oda akarok feküdni mellé mégis, de azt mondja, hogy attól rosszul lesz – mármint fizikailag –, úgyhogy megint elfog a szomorúság, a mély csalódottság és elmegyek.'],
            ['dream' => 'A régi szobámban voltunk, ahol felnőttem. Jött hozzám egy fotós, egy idősebb férfi, akivel össze kellett állítanunk egy címlapszerűséget. Azt javasolta, hog különböző könyvek címlapjait használjuk a fotózáshoz és azokat montázsoljuk össze. Levettem egyet az ágyam fölötti polcról, de nem igazán tetszett, próbáltam ellenkezni, hogy jaj, könyvek, ez olyan elcsépelt. De ő makacs volt, és nem engedett. Tekeregtem az ágyban félmeztelenül, csak egy póló volt rajtam, alul semmi, amikor valahogy megjelent K és elkezdtünk összefonódva egymáshoz érni. Teljesen fel voltam izgulva, de közben úgy csináltunk, mintha mi se történt volna, beszélgettünk a borítókról, könyvekről aztán elsötétült a jelenet.'],
            ['dream' => 'B-vel volt találkozóm, ahova siettem. Egy óriási metróhálózaton kellett keresztülmennem, magas mozgólépcsők, tekervényes folyosók, lebegőhidak és alagútrendszerek kavalkádjában. Amikor felértem a találkozási ponthoz, bár tudtam hol áll, mégis arrébb álltam meg és elkezdtem a telefonomon scrollozni, miközben egyre azt gondoltam, hogy ez hosszú tíz perceket fog elvenni az időmből és elkések. Aztán találkoztunk és kitaláltam valami alibit, miért késtem, ő magához szorított és tudtam, úgy kell tennem, hogy érezze, hogy érzem. Amikor elváltunk, olyan volt, mintha egy blokk feloldódott volna a közösségi média felületén és egy csomó olyan képet is láthattam róla és az új barátnőjéről, amiket korábban nem.'],
            ['dream' => 'András ott áll a KiBu hátsó udvarán, a darts tábla előtt. Hosszan nézem, hogy odamenjek-e hozzá, várom, hogy észrevegyen. Még mindig nem rendezték a fél éve leadott számlámat, ezzel akarom fárasztani, de inkább csak távolról nézem.'],
            ['dream' => 'Egy ügyvédi irodában vagyunk, valami szerződést kellene aláírni. Minden flottul megy, kedves az ügyvéd. Aztán mikor kész vagyunk, már csak a nyomtatásra várunk. Közben kérdezem, mit fizetek, erre valami horribilis összeget mond, de mondja, hogy várjuk meg, amint kinyomtatva lesz a szerződés. Csak nem akar elkészülni, közben látom, hogy az ár egyre emelkedik, szinte pörög. Mondom ez nem fair, ez nem az én hibám. Közben hív egy nyomtató szerelőt, és csak nem sikerül a művelet, de a számla csak pörög tovább. Közben már este lett, az adminisztrátorok lefeküdtek, csak várunk. Akkor nálam betelt a pohár, elkezdtem kiabálni, hogy mégis, mit képzel? Semmi munkáért ennyi pénzt. Mi minden pénzért keményen megdolgoztunk. Azt mondja, őt nem érdekli, menjek máshová, neki ennyi a bére. Mondom ez nem igazság, én is tanultam annyit mint ő, bezzeg nekem 1500 Ft volt az óradíjam, és mennyit kellett azért dolgozni. Kiabáltunk.'],
            ['dream' => 'A Vízügyhöz kell vinnem valami információt, de előtte valakivel beszélnem kell. Az illetőt hiába hívom, nem érem el sehogy. A mobilomon mindössze 1 nyomógomb volt, bármit csináltam vele, nem tudtam kapcsolatba kerülni az illetővel. Közben már többször üzentek a Vízügytől, hogy nagyon várnak, miért nem jövök. Amikor végre sikerült elérni az illetőt, akkor a környezeti zaj miatt nem hallottam semmit, aztán valaki bekapcsolta a porszívót, megint nem hallottam semmit. Ezzel kínlódtam egész éjszaka, mire felébredtem.'],
            ['dream' => 'Berlinben voltam és az volt a helyzet, hogy anyukámmal és a F-val közösen interjút kell készítenünk Ai Wei Wei-jel. Anyukámmal összevesztem még útközben, úgyhogy ő lelépett. A F-val késésben voltunk, így taxival mentünk. AW azt mondta a telefonba, hogy a stúdióját egy kikötőben találjuk egy Spar mellett. Felmentünk a csigalépcsőn, tök sokan vártak nála. Egy teli váróterem volt zöld székekkel. Többen ott voltak a kurzusról is.'],
            ['dream' => 'A régi házban laktunk, a Bartók Béla úton. A mamáék még éltek, de a gyerekek is megszülettek már. Sz kb. 8 éves lehetett. Emlékszem a ruhájára, a hajára. Egyszer egy idegen ember jött, egy szőke sörényes lóval az ablak alatt. Azt mondta, hogy meglovagoltatja  a gyerekeket. Én nagyon tiltakoztam, hogy tűnjön el innen, itt semmi keresnivalójuk idegeneknek. Ám Sz nagyon akart lovagolni és nem hallgatott rám. Nagyon rossz érzésem volt. Tehetetlennek éreztem magam, féltem hogy baj éri. Kiabáltam vele, hogy ez egy rossz ember. De nem hitte el. Ekkor dühömben és tehetetlenségemben pofon ütöttem. De a lendület után az erő elmaradt, szinte visszapattantak az ütéseim. Többször is megpróbáltam, nem tudtam megpofozni.']
        ];

        DB::table('dreams')->insert($dreams);

    }
}
